[build]
  command = "curl -sL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.5-stable.tar.xz | tar -xz -C $HOME && export PATH=\"$HOME/flutter/bin:$PATH\" && flutter doctor && flutter pub get && flutter build web"
  publish = "build/web"
