[build]
  command = "curl -sL https://storage.googleapis.com/download.flutter.dev/flutter_linux_3.10.0-stable.tar.xz | tar -xz -C $HOME && \
  export PATH=\"$HOME/flutter/bin:$PATH\" && \
  flutter doctor && \
  flutter pub get && \
  flutter build web"
  publish = "build/web"

[context.production.environment]
  FLUTTER_VERSION = "3.24.4"  # 使用するFlutterのバージョン
